[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "latentforce-extractors"
version = "1.0"
description = "Python client for Extractors.ai"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Aravind Jayendran", email = "aravind@latantforce.ai"}
]
dependencies = [
    "requests",
    "openai",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["latentforce_extractors"]