[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cassia_rag"
version = "0.1.3"
description = "A tool for cell type annotation using RAG"
readme = "README.md"
authors = [{name = "Lingxin Cheng", email = "lcheng74@wisc.edu"}]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "owlready2==0.47",
    "pandas==2.2.2",
    "langchain-openai==0.2.2",
    "langchain-anthropic==0.2.3",
    "langchain-community==0.3.2",
    "langchain-chroma==0.1.4",
    "langchain-core==0.3.10",
    "langchain-text-splitters==0.3.0",
    "langchain==0.3.3",
    "tqdm==4.66.4"
]
requires-python = ">=3.10"

#[project.urls]
#Homepage = "https://github.com/michal-kuklinski/cassia_rag" 