[project]
name = "funapi"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "funutil>=1.0.33", "openapi-python-client>=0.21.0",]
