[tool.poetry]
name = "tian_template"
version = "0.1.1"
description = "python.thienhang.com"
authors = ["open-thienhang-com"]
readme = "README.md"
packages = [{ include = "tian_hello" }]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
