[project]
name = "aixploit"
version = "1.1.4"
description = "AI redTeaming Python library"
authors = [{ name = "aintrust", email = "contact@aintrust.ai" }]
license = { text = "GPL-3.0" }
readme = "README.md"
keywords = ["AI", "redteaming", "AI redteaming", "AI redteam", "AI redteaming library", "AI redteam library","LLM Guardrails", "LLM Security", "LLM", "LLMs"]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "annotated-types==0.7.0",
    "anyio==4.6.2.post1",
    "backports.tarfile==1.2.0",
    "black==24.8.0",
    "certifi==2024.8.30",
    "charset-normalizer==3.4.0",
    "distro==1.9.0",
    "docutils==0.21.2",
    "filelock==3.16.1",
    "fsspec==2024.10.0",
    "h11==0.14.0",
    "httpcore==1.0.6",
    "httpx==0.27.2",
    "huggingface-hub==0.26.3",
    "idna==3.10",
    "importlib_metadata==8.5.0",
    "jaraco.classes==3.4.0",
    "jaraco.context==6.0.1",
    "jaraco.functools==4.1.0",
    "Jinja2==3.1.4",
    "jiter==0.7.0",
    "joblib==1.4.2",
    "keyring==25.5.0",
    "markdown-it-py==3.0.0",
    "MarkupSafe==3.0.2",
    "readme_renderer==44.0",
    "regex==2024.11.6",
    "requests==2.32.3",
    "requests-toolbelt==1.0.0",
    "rfc3986==2.0.0",
    "rich==13.9.4",
    "safetensors==0.4.5",
    "scikit-learn==1.5.2",
    "scipy==1.14.1",
    "sentence-transformers==3.3.1",
    "sniffio==1.3.1",
    "sympy==1.13.1",
    "threadpoolctl==3.5.0",
    "tiktoken==0.8.0",
    "tokenizers==0.20.3",
    "torch==2.5.1",
    "tqdm==4.66.6",
    "transformers==4.46.3",
    "twine==5.1.1",
    "typing_extensions==4.12.2",
    "urllib3==2.2.3",
    "zipp==3.21.0",
]

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[tool.black]
line-length = 88  # You can adjust this value as needed