[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/anas-shakeel/maketree-cli"
Source = "https://github.com/anas-shakeel/maketree-cli"

[project]
name = "maketree"
version = "1.0.2"
description = "A CLI tool to create directory structures from a structure file."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Anas Shakeel", email = "srdranas456@gmail.com" }
]
requires-python = ">=3.8"
keywords = ["cli", "directory", "automation", "file-system"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Utilities"
]
dependencies = []

[project.scripts]
maketree = "maketree.cli:main"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
include-package-data = true