[project]
name = "gemmoai"
version = "0.1.4"
description = "GemmoAI Python Library"
readme = "README.md"
authors = [
    { name = "Giacomo Piccinini", email = "giacomo.piccinini@gemmo.ai" },
    { name = "Alessio Franchi", email = "alessio.franchi@gemmo.ai" },
    { name = "Elisa Castelli", email = "elisa.castelli@gemmo.ai" },
    { name = "NicolÃ² Pisanu", email = "nicolo.pisanu@gemmo.ai" }
]
requires-python = ">=3.11"
dependencies = [
    "pymupdf>=1.24.14",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
