[project]
name = "obsidian-brain"
version = "0.1.3"
description = "Give claude access to your obsidian brain"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
 "flagembedding>=1.3.2",
 "httpx>=0.27.2",
 "lancedb>=0.16.0",
 "langchain-community>=0.3.8",
 "langchain-core>=0.3.21",
 "markdown>=3.7",
 "mcp>=1.0.0",
 "rank-bm25>=0.2.2",
 "sentence-transformers>=3.3.1",
 "unstructured>=0.16.8",
 "watchfiles>=1.0.0",
 "whoosh>=2.7.4",
]
[[project.authors]]
name = "spongeboi"
email = "hi@spongeboi.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
obsidian-brain = "obsidian_brain:main"
